### ISSUE TITLE
".git" is to big and maybe has binaries in it

### ISSUE THREAD

**Issue by buhtz** [devongarde/ssc#57]
Hello,

when doing "git clone" it downloads more than 1.3 GB (75% of the objects). This is definitely to much. There might be binary objects in the history? I stopped the cloning and did not finish it.

**Comment by devongarde** [comment]
I used to include specifications as PDFs, which ended up taking a lot of space. I removed them, but they're clearly still in the .git history. I'm not quite sure how to erase them, although I'm know it's possible, so I'll look into that and get back to you.

In the meantime, can I suggest you simply clone the current version?

Also, current and earlier versions are available at https://ssc.lu/. The current version there is 22M.

**Comment by devongarde** [comment]
Please try now. Note the comment in README.
